# Generated by Django 4.1 on 2022-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
