# Generated by Django 4.1 on 2022-08-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0004_alter_company_address_alter_company_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
