# Generated by Django 4.1 on 2022-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0005_alter_company_address_alter_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
