# Generated by Django 4.1 on 2022-08-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0006_alter_salary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='snippet',
            new_name='requirement',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility',
            field=models.TextField(blank=True),
        ),
    ]
