# Generated by Django 4.1 on 2022-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0007_rename_snippet_vacancy_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='role',
            field=models.ManyToManyField(blank=True, to='parser_hh.role'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='parser_hh.specialization'),
        ),
    ]
