# Generated by Django 4.1 on 2022-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0008_vacancy_role_vacancy_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
