# Generated by Django 4.1 on 2022-08-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0009_remove_vacancy_role_delete_role_vacancy_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_hh.city')),
                ('experience', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.experience')),
                ('salary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.salary')),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.schedule')),
            ],
        ),
    ]
