# Generated by Django 4.1 on 2022-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0010_alter_vacancy_role_alter_vacancy_url_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='city',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='params',
            name='salary',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
