# Generated by Django 4.1 on 2022-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0011_alter_params_city_alter_params_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='params',
            name='schedule',
        ),
        migrations.AddField(
            model_name='params',
            name='experience',
            field=models.ManyToManyField(blank=True, to='parser_hh.experience'),
        ),
        migrations.AddField(
            model_name='params',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='parser_hh.schedule'),
        ),
    ]
