# Generated by Django 4.1 on 2022-08-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0013_remove_params_experience_remove_params_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='params',
            name='schedule',
        ),
    ]
