# Generated by Django 4.1 on 2022-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0014_remove_params_experience_remove_params_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Params',
            new_name='Param',
        ),
    ]
