# Generated by Django 4.1 on 2022-08-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0018_alter_param_experience_alter_param_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='experience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.experience'),
        ),
        migrations.AlterField(
            model_name='param',
            name='schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser_hh.schedule'),
        ),
    ]
