# Generated by Django 4.1 on 2022-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0020_alter_param_experience_alter_param_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='city',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='salary',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
