# Generated by Django 4.1 on 2022-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0022_alter_param_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='salary',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
